### ISSUE TITLE
Problem when dismissing the View that is displaying the video

### ISSUE THREAD

**Issue by BlaXun** [otalk/TLKSimpleWebRTC#2]
Hi there,

I took your example and did some layouting without thouching the original code.
In my App I now have a input field for a room name. Pressing a button will move to the view in which the video is shown. Everything is fine up to now...but, how would I CORRECTLY end the stream, close connection to the signaling server and then dismiss the view?

I tried this but I always get errors in a C Lib MediaStreamProxy ....its tryin to access something that does not exist anymore at this point.

Also, in RTCVideoRenderer.h the delegate is of "strong" type...is this intended?
@property(nonatomic, strong) id<RTCVideoRendererDelegate> delegate;

Edit:
I think its bout the MediaStreams in the signalingServer ....I will try to manually remove the video and audio tracks from each stream before removing the view.

Still hope u guys can give me a hint here :)

**Comment by pablogeek** [comment]
@BlaXun I'm having the same problem, did you fix this?
