### ISSUE TITLE
leaveroom will disconnect, joinroom won't connect

### ISSUE THREAD

**Issue by evermeer** [otalk/TLKSimpleWebRTC#7]
In TLKSocketIOSignaling.m the leaveroom method will disconnect the soccet. The join room will not connect the socket. Because of this it's not possible to leave and reconnect. When removing the disconnect line in the leaveroom it's possible to do this.

It think it would be better if the connect was moved to the joinroom method so that the connection won't be open if it's not needed.

**Comment by pablogeek** [comment]
Did you have problems with crashes after disconnection? @evermeer

**Comment by evermeer** [comment]
@pablogeek No, it just disconnects
